spring:
  datasource:
    url: mariadb.agrigaia-ui.svc.cluster.local
    driver-class-name: org.mariadb.jdbc.Driver
    username: agrigaia
    password: agrigaia
#  jpa:
#    hibernate:
#      ddl-auto: # update
#    show-sql: # true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: # https://account.platform.agri-gaia.com/auth/realms/agri-gaia
#
#logging:
#  level:
#    de.agrigaia.platform: TRACE
#
#agrigaia-platform:
#  allowed-origins: #
#    client-id: # platform
