spring:
  datasource:
    url: jdbc:mariadb://mariadb.ag-test-platform.svc.cluster.local/sampledb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://account.platform.agri-gaia.com/realms/agri-gaia-platform
#          jwk-set-uri: https://account.platform.agri-gaia.com/auth/realms/agri-gaia/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: -1 # This property sets the maximum size of an individual file that can be uploaded in a multipart request. If a file is larger than this size, the upload will fail with a MaxUploadSizeExceededException. Setting this property to -1 removes the file size limit.
      max-request-size: -1 #  This property sets the maximum size of the entire multipart request, which includes all files and other form data. If the request is larger than this size, the upload will fail with a MaxUploadSizeExceededException. Setting this property to -1 removes the request size limit.

#logging:
#  level:
#    de: DEBUG
#    com: DEBUG
#    org: DEBUG
#    de.agrigaia.platform: DEBUG

agrigaia-platform:
  allowed-origins: '*'
  client-id: ag-test-platform-ui

  keycloak:
    serverUrl: # URL Authentication server
    realm: #
    clientId: # realm-management
    clientSecret: #
    userName: # Technical user name
    password: # Technical user password
  minio:
    url: https://minio-test-api.platform.agri-gaia.com #
    technicalUserAccessKey: # minio - identity - service accounts - access key
    technicalUserSecretKey: # minio - identity - service accounts - secret key
  coopSpaces:
    createCoopSpaceUrl: https://create-cooperation-room-eventsource.platform.agri-gaia.com #
    deleteCoopSpaceUrl: https://delete-cooperation-room-eventsource.platform.agri-gaia.com #

server:
  servlet:
    context-path: /api
