spring:
  datasource:
    url: # jdbc:mariadb://127.0.0.1:3306/agrigaia_platform_db
    driver-class-name: # org.mariadb.jdbc.Driver
    username: # agrigaia
    password: # agrigaia
  jpa:
    hibernate:
      ddl-auto: # update
    show-sql: # true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: # https://account.platform.agri-gaia.com/auth/realms/agri-gaia

logging:
  level:
    de.agrigaia.platform: TRACE

agrigaia-platform:
  allowed-origins: #
    client-id: # platform
    
resources:
  cpu: 2
  memory_gb: 2.0
